#!/bin/sh

if [ $1 = "gui"]
then
  java --module-path=/home/luca/Documents/HomeStuff/JavaFX/javafx-sdk-20.0.2/lib --add-modules javafx.controls,javafx.fxml -cp ./target/PathTracerGUI.jar luca.raytracing.App
else
  java --module-path=/home/luca/Documents/HomeStuff/JavaFX/javafx-sdk-20.0.2/lib --add-modules javafx.controls,javafx.fxml -cp ./target/PathTracerGUI.jar luca.raytracing.CommandLine
fi

